import { NextResponse } from 'next/server';

const featureUsageData = {
  barChart: [
    { name: 'Catat Pengeluaran', count: 845, color: '#f59e0b' },
    { name: 'Budget', count: 620, color: '#3b82f6' },
    { name: 'Nabung', count: 430, color: '#10b981' },
    { name: 'AI Notifikasi', count: 380, color: '#a855f7' },
    { name: 'Rekap Aktivitas', count: 710, color: '#f97316' },
  ],
  pieChart: [
    { name: 'Catat Pengeluaran', percentage: 28, color: '#f59e0b' },
    { name: 'Budget', percentage: 20, color: '#3b82f6' },
    { name: 'Rekap Aktivitas', percentage: 18, color: '#06b6d4' },
    { name: 'Nabung', percentage: 15, color: '#10b981' },
    { name: 'AI Notifikasi', percentage: 12, color: '#a855f7' },
    { name: 'Lainnya', percentage: 7, color: '#facc15' },
  ],
  totalActivities: 8430,
  details: [
    {
      id: '1',
      name: 'Catat Pengeluaran',
      desc: 'Transaksi harian & kwitansi',
      iconType: 'receipt',
      iconBg: 'bg-amber-100/80 text-amber-600',
      barColor: 'bg-amber-500',
      usage: '845 sesi',
      growth: '+14.2%',
      retention: 88,
      peakHour: '19:30 - 21:00 WIB',
      status: 'Tinggi',
      statusBg: 'bg-emerald-100/70 text-emerald-600',
    },
    {
      id: '2',
      name: 'Rekap Aktivitas',
      desc: 'Laporan arus kas & grafik',
      iconType: 'pie-chart',
      iconBg: 'bg-slate-100 text-slate-600',
      barColor: 'bg-orange-500',
      usage: '710 sesi',
      growth: '+8.6%',
      retention: 76,
      peakHour: '20:00 - 22:00 WIB',
      status: 'Stabil',
      statusBg: 'bg-emerald-100/70 text-emerald-600',
    },
    {
      id: '3',
      name: 'Budget',
      desc: 'Limit anggaran pos bulanan',
      iconType: 'wallet',
      iconBg: 'bg-indigo-50 text-indigo-500',
      barColor: 'bg-blue-500',
      usage: '620 sesi',
      growth: '+5.3%',
      retention: 70,
      peakHour: '08:00 - 10:00 WIB',
      status: 'Stabil',
      statusBg: 'bg-emerald-100/70 text-emerald-600',
    },
    {
      id: '4',
      name: 'Nabung',
      desc: 'Target tabungan & investasi',
      iconType: 'piggy',
      iconBg: 'bg-emerald-100/80 text-emerald-600',
      barColor: 'bg-emerald-500',
      usage: '430 sesi',
      growth: '+11.8%',
      retention: 64,
      peakHour: '12:00 - 14:00 WIB',
      status: 'Bertumbuh',
      statusBg: 'bg-amber-100/80 text-amber-700',
    },
    {
      id: '5',
      name: 'AI Notifikasi',
      desc: 'Insight rekomendasi & budget alert',
      iconType: 'bot',
      iconBg: 'bg-purple-100/80 text-purple-600',
      barColor: 'bg-purple-500',
      usage: '380 sesi',
      growth: '+22.4%',
      retention: 58,
      peakHour: '07:00 - 08:30 WIB',
      status: 'Tinggi MoM',
      statusBg: 'bg-amber-100/80 text-amber-700',
    },
  ],
};

export async function GET() {
  return NextResponse.json({
    success: true,
    data: featureUsageData,
  });
}